/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#09090b",
        "primary-container": "#18181b",
        "on-primary": "#ffffff",
        "on-primary-container": "#09090b",
        "primary-fixed": "#f4f4f5",
        "primary-fixed-dim": "#e4e4e7",
        "inverse-primary": "#fafafa",
        "surface": "#f8f9fa",
        "surface-dim": "#e4e4e7",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f6",
        "surface-container": "#eceef1",
        "surface-container-high": "#e2e5ea",
        "surface-container-highest": "#d5dae1",
        "surface-variant": "#f1f3f5",
        "on-surface": "#09090b",
        "on-surface-variant": "#52525b",
        "inverse-surface": "#09090b",
        "inverse-on-surface": "#f4f4f5",
        "secondary": "#52525b",
        "on-secondary": "#ffffff",
        "secondary-container": "#f4f4f5",
        "on-secondary-container": "#27272a",
        "secondary-fixed": "#f4f4f5",
        "secondary-fixed-dim": "#e4e4e7",
        "tertiary": "#2563eb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#eff6ff",
        "on-tertiary-container": "#1d4ed8",
        "tertiary-fixed": "#dbeafe",
        "tertiary-fixed-dim": "#bfdbfe",
        "background": "#f8f9fa",
        "on-background": "#09090b",
        "outline": "#71717a",
        "outline-variant": "#e4e4e7",
        "error": "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        "brand-dark": "#09090b",
        "brand-gold": "#f59e0b",
        "brand-cream": "#ffffff",
        "accent-blue": "#2563eb",
        "accent-emerald": "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      boxShadow: {
        card: "0 8px 24px -4px rgba(21, 26, 31, 0.05), 0 2px 6px -1px rgba(21, 26, 31, 0.03)",
        "card-hover": "0 20px 40px -8px rgba(21, 26, 31, 0.10), 0 6px 16px -3px rgba(21, 26, 31, 0.05)",
        "nav-dock": "0 -4px 24px rgba(21, 26, 31, 0.08)",
        "dropdown": "0 16px 48px -4px rgba(21, 26, 31, 0.12), 0 4px 16px -2px rgba(21, 26, 31, 0.06)",
        "glow-primary": "0 0 24px -4px rgba(244, 122, 32, 0.35)",
        "glow-gold": "0 0 24px -4px rgba(255, 181, 46, 0.40)",
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
        "pulse-subtle": "pulse-subtle 3s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.85" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
    },
  },
  plugins: [],
}
